// src/features/posts/postsSlice.js
//
// Implements Assignments 1, 2, 3 and 4 from the experiment sheet:
//   1. Redux Slice Implementation  -> createSlice + add/update/delete reducers
//   2. Async Data Handling         -> createAsyncThunk (pending/fulfilled/rejected)
//   3. State Normalization         -> createEntityAdapter (ids[] + entities{})
//   4. Selector Optimization       -> createSelector (reselect) memoized selectors

import {
  createSlice,
  createAsyncThunk,
  createEntityAdapter,
  createSelector,
  nanoid,
} from "@reduxjs/toolkit";
import { apiFetchPosts, apiCreatePost } from "../../api/mockApi";

// ---------------------------------------------------------------------------
// 1. Entity Adapter — flattens posts into { ids: [...], entities: { id: post } }
// ---------------------------------------------------------------------------
const postsAdapter = createEntityAdapter({
  // keep the list sorted by schedule date, most recent first
  sortComparer: (a, b) => a.scheduledAt.localeCompare(b.scheduledAt),
});

const initialState = postsAdapter.getInitialState({
  loading: "idle", // 'idle' | 'pending' | 'succeeded' | 'failed'
  error: null,
});

// ---------------------------------------------------------------------------
// 2. Async Thunks — simulate API-based data fetching / creation
// ---------------------------------------------------------------------------
export const fetchPosts = createAsyncThunk(
  "posts/fetchPosts",
  async (_args, { rejectWithValue }) => {
    try {
      const posts = await apiFetchPosts();
      return posts;
    } catch (err) {
      return rejectWithValue(err.message);
    }
  }
);

export const createPost = createAsyncThunk(
  "posts/createPost",
  async (postDraft) => {
    const saved = await apiCreatePost({ id: nanoid(), ...postDraft });
    return saved;
  }
);

// ---------------------------------------------------------------------------
// Slice — synchronous CRUD reducers + async lifecycle via extraReducers
// ---------------------------------------------------------------------------
const postsSlice = createSlice({
  name: "posts",
  initialState,
  reducers: {
    // Assignment 1: add / update / delete
    postAdded: {
      reducer(state, action) {
        postsAdapter.addOne(state, action.payload);
      },
      prepare(post) {
        return {
          payload: {
            id: nanoid(),
            status: "draft",
            scheduledAt: new Date().toISOString(),
            ...post,
          },
        };
      },
    },
    postUpdated: postsAdapter.updateOne, // expects { id, changes }
    postDeleted: postsAdapter.removeOne, // expects id
    postsCleared: postsAdapter.removeAll,
  },
  extraReducers: (builder) => {
    builder
      // fetchPosts lifecycle
      .addCase(fetchPosts.pending, (state) => {
        state.loading = "pending";
        state.error = null;
      })
      .addCase(fetchPosts.fulfilled, (state, action) => {
        state.loading = "succeeded";
        postsAdapter.setAll(state, action.payload); // normalizes the array
      })
      .addCase(fetchPosts.rejected, (state, action) => {
        state.loading = "failed";
        state.error = action.payload ?? action.error.message;
      })
      // createPost lifecycle
      .addCase(createPost.fulfilled, (state, action) => {
        postsAdapter.addOne(state, action.payload);
      });
  },
});

export const { postAdded, postUpdated, postDeleted, postsCleared } =
  postsSlice.actions;

export default postsSlice.reducer;

// ---------------------------------------------------------------------------
// 3. Base selectors generated by the entity adapter
//    (selectAll, selectById, selectIds, selectEntities, selectTotal)
// ---------------------------------------------------------------------------
export const postsSelectors = postsAdapter.getSelectors(
  (state) => state.posts
);

export const selectPostsLoading = (state) => state.posts.loading;
export const selectPostsError = (state) => state.posts.error;

// ---------------------------------------------------------------------------
// 4. Derived / memoized selectors (Assignment 4)
//    createSelector only recomputes when its inputs actually change.
// ---------------------------------------------------------------------------

// Short posts — used e.g. by a compact "quick view" widget
export const selectShortPosts = createSelector(
  [postsSelectors.selectAll],
  (posts) => posts.filter((post) => post.content.length < 100)
);

// Posts grouped by platform — powers the calendar / analytics views
export const selectPostsByPlatform = createSelector(
  [postsSelectors.selectAll],
  (posts) => {
    const grouped = {};
    for (const post of posts) {
      if (!grouped[post.platformId]) grouped[post.platformId] = [];
      grouped[post.platformId].push(post);
    }
    return grouped;
  }
);

// Analytics: post count + average length per status
export const selectPostAnalytics = createSelector(
  [postsSelectors.selectAll],
  (posts) => {
    const byStatus = { draft: [], scheduled: [], published: [] };
    for (const post of posts) {
      (byStatus[post.status] ??= []).push(post);
    }
    const summarize = (list) => ({
      count: list.length,
      avgLength: list.length
        ? Math.round(
            list.reduce((sum, p) => sum + p.content.length, 0) / list.length
          )
        : 0,
    });
    return {
      draft: summarize(byStatus.draft),
      scheduled: summarize(byStatus.scheduled),
      published: summarize(byStatus.published),
      total: posts.length,
    };
  }
);

// Parameterized selector factory — posts for a single platform id
export const makeSelectPostsForPlatform = (platformId) =>
  createSelector([selectPostsByPlatform], (grouped) => grouped[platformId] ?? []);
